### PR TITLE
Fixup code for use with rackup gem (may be used with rack 3)

### LINKED ISSUE #3057: Using rack 3. Receive deprecation warning.
**Describe the bug**
deprecation warning: "Rack::Handler is deprecated and replaced by Rackup::Handler"

Spent a little time to determine the issue. The issue seems to be when rackup.rb requires puma.rb. puma.rb does a require on rack/handler.rb on about line 3. rack/handler.rb throws deprecation warning.

**Expected behavior**
App should start without deprecation warning.

**Desktop (please complete the following information):**
 - OS: Mac M1 arm
 - Puma Version 6.0.2
 - rack version 3.0.3

~Marvin Foster 
email: mmarvb7@gmail.com or marvinfoster@finsync.com

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description

Rack v2 included the files needed to use `rackup` from the command line.  With Rack v3, it is now a separate gem, and the namespace has changed.

Re tests, when Rack v3 was released, we (ok, I) blocked  [test/test_rack_handler](https://github.com/puma/puma/blame/3f4e3c8ca689e39218459836b939c39fa81e2692/test/test_rack_handler.rb#L5) from running with Rack v3, so tests do exist.  This PR unblocks the tests.

The changes to `lib/rack/handler/puma.rb` look excessive.  This PR is taking the previous code, and turning it into a HEREDOC, so it can be used in `module_eval`.  This is the work-around to allow it to be placed in either the `Rack::Handler` or the `Rackup::Handler` namespace.

Adjust code to work with both.

**Note:** labeled as a 'bug', not sure...

Closes #3057 

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

File: lib/puma/rack_default.rb [hunk 1]
```diff
@@ -2,8 +2,20 @@
 
 require_relative '../rack/handler/puma'
 
-module Rack::Handler
-  def self.default(options = {})
-    Rack::Handler::Puma
+if Object.const_defined? :Rackup
```
Comment (choallin) [inline lib/puma/rack_default.rb:5]: Although this works, I think testing for Rack version 3 is more meaningful, because this tells the reader that this was implemented in response to a change in the new Rack version.

File: lib/rack/handler/puma.rb [hunk 2]
```diff
@@ -1,114 +1,118 @@
...
-          end
+# Code below is 'odd', but don't want to define a top level constant
+
+if Object.const_defined? :Rackup
+  require 'rackup/handler'
+  ::Rackup::Handler
+else
+  require 'rack/handler'
+  ::Rack::Handler
+end.module_eval <<'HEREDOC'
```
Comment (choallin) [inline lib/rack/handler/puma.rb:11]: To get rid of this `module_eval` we could create a new lib/rackup/handler.rb file that is required here. The file could either duplicate the code, or we are putting the code inside a module and are including this new module inside the new rackup/handler and rack/handler :thinking:

Comment (MSP-Greg) [reply lib/rack/handler/puma.rb]: The cleanest way is with `modulfe_eval`, but that also 'hides' the code from RuboCop, etc.  I changed the code to use include.  See the last commit.

**Comment by MSP-Greg** [comment]
A note for those who haven't looked at rack/rackup code, as of the current version of rackup (2.0.0), the code by default tries `require 'rack/handler/puma'` first, so the file path is fixed.  If Puma has been activated, that require statement succeeds...

File: lib/puma/rack_default.rb [hunk 3]
```diff
@@ -2,8 +2,23 @@
...
+elsif Object.const_defined?(:Rack) && Rack::RELEASE < '3'
+  module Rack
+    module Handler
+      def self.default(options = {})
+        ::Rack::Handler::Puma
+      end
+    end
+  end
+else
+  raise "Rack 3 must be used with the Rackup gem"
```
Comment (nateberkopec) [inline lib/puma/rack_default.rb:23]: Error message could be something like `you must install the rackup gem.`, i.e. tell the user what to do exactly

File: lib/rack/handler/puma.rb [hunk 4]
```diff
@@ -1,114 +1,136 @@
...
+          config.port port, host
         end
       end
     end
+  end
+end
 
-    register :puma, Puma
+# rackup was removed in Rack 3, it is now a separate gem
+if Object.const_defined? :Rackup
```
Comment (nateberkopec) [inline lib/rack/handler/puma.rb:112]: Can we just combine this with what's in `rack_default`? 🤔

File: test/test_rack_handler.rb [hunk 5]
```diff
@@ -2,16 +2,22 @@
 
 require "rack"
 
-if Rack::RELEASE < '3'
-
-  require "rack/handler/puma"
+module TestRackUp
+  if Rack::RELEASE < '3'
+    require "rack/handler/puma"
```
Comment (nateberkopec) [inline test/test_rack_handler.rb:7]: this can be moved out of the if statement because you use it in both branches

File: test/test_rack_handler.rb [hunk 6]
```diff
@@ -2,16 +2,22 @@
...
+    RACK_HANDLER_MOD = ::Rack::Handler
+  else
+    require "rackup"
+    require "rack/handler/puma"
+    RACK_HANDLER_MOD = ::Rackup::Handler
```
Comment (nateberkopec) [inline test/test_rack_handler.rb:12]: Maybe we could just test `Puma::RackHandler` directly for most of the tests instead?

File: test/test_rack_handler.rb (hunk 5 above)
Comment (MSP-Greg) [reply test/test_rack_handler.rb]: Updated, see commit 'Changes per comments'

File: test/test_rack_handler.rb (hunk 6 above)
Comment (MSP-Greg) [reply test/test_rack_handler.rb:9]: Two methods are called in `RACK_HANDLER_MOD`, `register` and `get`.  If we want to verify that things work with Rack/Rackup, it would be good to continue doing so...

File: lib/rack/handler/puma.rb (hunk 4 above)
Comment (MSP-Greg) [reply lib/rack/handler/puma.rb:112]: No.  As mentioned above, Rackup currently will look for several servers, and Puma is the first one.  It determines if Puma is available by requiring `rack/handler/puma`.

For info on `rack_default`, see https://github.com/puma/puma/pull/194.

File: lib/puma/rack_default.rb (hunk 3 above)
Comment (MSP-Greg) [reply lib/puma/rack_default.rb:23]: Updated, see commit 'Changes per comments'

File: lib/puma/rack_default.rb (hunk 1 above)
Comment (MSP-Greg) [reply lib/puma/rack_default.rb:6]: Sorry, I thought I responded.  The rackup namespace needs to be defined.  The Rack v3 gem could be loaded, but unless the rackup gem is also loaded, this will fail.  I added a comment.

**Comment by MSP-Greg** [comment]
Rebased

**Comment by ioquatix** [comment]
Just FYI, I expect the rackup gem to evolve more rapidly than it has before. While Rack v2 and Rackup gems are currently aligned, I imagine the handler implementation will diverge in the future (or be extended I compatible ways which are not part of the Rack 2 implementation).
