### PR TITLE
Fix `prune_bundler` stripping user-configured `BUNDLE_*` env vars on re-exec

### LINKED ISSUE #3744: prune_bundler started failing in Puma 7.0.0
Started the investigation as @schneems suggedted in https://github.com/puma/puma/issues/3730#issuecomment-3282527469

**Describe the bug**
`prune_bundler` started failing in Puma 7.0.0 (bisecting found that the breaking PR is https://github.com/puma/puma/pull/3297):
```
[2092] + Gemfile in context: /rails/Gemfile
[2092] ! Unable to start worker
[2092] Could not find web-console-4.2.1, brakeman-7.1.0, bundler-audit-0.9.2, rubocop-1.80.2, rubocop-capybara-2.22.1, rubocop-factory_bot-2.27.1, rubocop-performance-1.26.0, rubocop-rails-2.33.3, rubocop-rake-0.7.1, rubocop-rspec-3.7.0, rubocop-rspec_rails-2.31.0, bindex-0.8.1, json-2.13.2, language_server-protocol-3.17.0.5, lint_roller-1.1.0, parallel-1.27.0, parser-3.3.9.0, rainbow-3.1.1, regexp_parser-2.11.2, rubocop-ast-1.46.0, ruby-progressbar-1.13.0, unicode-display_width-3.2.0, ast-2.4.3, prism-1.4.0, unicode-emoji-4.1.0 in locally installed gems
[2092] /usr/local/lib/ruby/site_ruby/3.4.0/bundler/definition.rb:683:in 'Bundler::Definition#materialize'
    /usr/local/lib/ruby/site_ruby/3.4.0/bundler/definition.rb:237:in 'Bundler::Definition#specs'
    /usr/local/lib/ruby/site_ruby/3.4.0/bundler/definition.rb:304:in 'Bundler::Definition#specs_for'
    /usr/local/lib/ruby/site_ruby/3.4.0/bundler/runtime.rb:18:in 'Bundler::Runtime#setup'
    /usr/local/lib/ruby/site_ruby/3.4.0/bundler.rb:167:in 'Bundler.setup'
    /usr/local/lib/ruby/site_ruby/3.4.0/bundler/setup.rb:32:in 'block in <top (required)>'
    /usr/local/lib/ruby/site_ruby/3.4.0/bundler/ui/shell.rb:173:in 'Bundler::UI::Shell#with_level'
    /usr/local/lib/ruby/site_ruby/3.4.0/bundler/ui/shell.rb:119:in 'Bundler::UI::Shell#silence'
    /usr/local/lib/ruby/site_ruby/3.4.0/bundler/setup.rb:32:in '<top (required)>'
    <internal:/usr/local/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
    <internal:/usr/local/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/configuration.rb:393:in 'Puma::Configuration#rack_builder'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/configuration.rb:411:in 'Puma::Configuration#load_rackup'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/configuration.rb:315:in 'Puma::Configuration#app'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/runner.rb:179:in 'Puma::Runner#app'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/runner.rb:183:in 'Puma::Runner#start_server'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/cluster/worker.rb:60:in 'Puma::Cluster::Worker#run'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/cluster.rb:230:in 'Puma::Cluster#worker'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/cluster.rb:106:in 'block in Puma::Cluster#spawn_worker'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/cluster.rb:106:in 'Kernel#fork'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/cluster.rb:106:in 'Puma::Cluster#spawn_worker'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/cluster.rb:86:in 'block in Puma::Cluster#spawn_workers'
    <internal:numeric>:257:in 'Integer#times'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/cluster.rb:79:in 'Puma::Cluster#spawn_workers'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/cluster.rb:182:in 'Puma::Cluster#check_workers'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/cluster.rb:469:in 'Puma::Cluster#run'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/launcher.rb:202:in 'Puma::Launcher#run'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/lib/puma/cli.rb:73:in 'Puma::CLI#run'
    /usr/local/bundle/ruby/3.4.0/bundler/gems/puma-6064d1535b22/bin/puma-wild:25:in '<main>'
[2092] Early termination of worker
```

**Puma config:**
```
threads_count = ENV.fetch("RAILS_MAX_THREADS", 3)
workers_count = Integer(ENV['WEB_CONCURRENCY'] || 0)
threads threads_count, threads_count

# Specifies the `worker_timeout` threshold that Puma will use to wait before
# terminating a worker in development environments.
#
worker_timeout 3600 if ENV.fetch("RAILS_ENV", "development") == "development"

# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
port ENV.fetch("PORT", 3000)
# bind 'ssl://localhost:3000'

# Specifies the `environment` that Puma will run in.
#
environment ENV.fetch("RAILS_ENV", "development")

if workers_count > 1
  workers workers_count
  prune_bundler
  fork_worker
end

# Allow puma to be restarted by `bin/rails restart` command.
plugin :tmp_restart

# Run the Solid Queue supervisor inside of Puma for single-server deployments
plugin :solid_queue if ENV["SOLID_QUEUE_IN_PUMA"]

# Specify the PID file. Defaults to tmp/pids/server.pid in development.
# In other environments, only set the PID file if requested.
pidfile ENV.fetch("PIDFILE", "tmp/pids/server.pid")

```

Puma is started from the Dockerfile:
```
CMD ["bundle", "exec", "puma", "-e", "production", "-C", "config/puma.rb"]
```

**To Reproduce**

Upgrade Puma on my application, https://github.com/texpert/camaleon_website, to 7.0.0, and do a deployment with Kamal. The app will start booting, and then crash, as shown in the logs above.

Commenting the `prune_bundler` command in Puma's config file, makes the application work normally.

**Expected behavior**
Expect the app to boot and work,

**Desktop (please complete the following information):**
 - Ubuntu 24.04
 - Puma Version 7.0.0 (or 7.0.0.pre1 `ref: '6064d1535b22404960fc5f06487ed232acfcbc9c'`)
 - Ruby 3.4.5
 - Rails 8.0.2.1
 - kamal (1.9.3)

It seems like the failures are on trying to find the gems that haven't been bundled, because the Dockerfile specifies `BUNDLE_WITHOUT="development:test"`.

### PR DESCRIPTION
**Pull request by joshuay03**
Closes #3744

When `prune_bundler` is configured, Puma re-execs itself via `puma-wild` using `Bundler.with_unbundled_env`, which strips all `BUNDLE_*` environment variables. Previously only `BUNDLE_GEMFILE` and `BUNDLE_APP_CONFIG` were explicitly restored, so user-set vars like `BUNDLE_WITHOUT` and `BUNDLE_DEPLOYMENT` were lost.

This causes workers to crash on boot. When a worker loads the app, `rack_builder` calls `require 'bundler/setup'` (because `PUMA_BUNDLER_PRUNED=1`). Without `BUNDLE_WITHOUT`, Bundler tries to activate all gem groups, including ones that were never installed (e.g. development and test in a Docker deployment), and raises `Bundler::GemNotFound`.

This was not caught before Puma 7 because a separate bug (fixed in #3297) caused `preload_app` to be incorrectly enabled alongside `prune_bundler` when workers were set via `WEB_CONCURRENCY`. With the app preloaded in the master process before the prune exec, `require 'bundler/setup'` was never called in workers post-prune. The fix in #3297 correctly sets `preload_app false` when `prune_bundler` is configured, which exposed this underlying issue.

The fix restores all `BUNDLE_*` vars from `Bundler.original_env` (the environment before `bundle exec` modified it) into the re-exec environment, so user-configured Bundler settings are preserved.

### CODE REVIEW

File: test/test_integration_cluster.rb [hunk 1]
```diff
@@ -471,6 +471,13 @@ def test_prune_bundler_with_multiple_workers
     assert_equal reply, "embedded app"
   end
 
+  def test_prune_bundler_preserves_bundle_env_vars
+    cli_server "-w #{workers} --prune-bundler test/rackup/bundle_without.ru",
+      env: { 'BUNDLE_WITHOUT' => 'development:test' }
+
+    assert_equal 'development:test', read_body(connect)
+  end
```
Comment (joshuay03) [inline test/test_integration_cluster.rb:479]: On main:
```
puma [main] bundle exec ruby -Itest test/test_integration_cluster.rb --name /test_prune_bundler_preserves_bundle_env_vars/
Run options: --name /test_prune_bundler_preserves_bundle_env_vars/ --seed 34712

# Running:

F

Fabulous run in 0.706427s, 1.4156 runs/s, 1.4156 assertions/s.
Errors & Failures:

  1) Failure:
TestIntegrationCluster#test_prune_bundler_preserves_bundle_env_vars [test/test_integration_cluster.rb:478]:
Expected: "development:test"
  Actual: "not_set"

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

**Review by texpert — APPROVED** [review]
