### PR TITLE
[fix] TLS verification hang on JRuby

### LINKED ISSUE #2729: JRuby verify_mode: peer (force_peer) hang
**Describe the bug**

Running with `verify_mode` (`!= none`) under JRuby leads to a no response from the sever, eventually the timeout kicks in.

**To Reproduce**

All `repro.rb` bits, including certificates available at: https://gist.github.com/kares/5da3aaea23f27af3a63cbb586771ca55

```ruby
require "puma"
require "puma/server"

class Application
  def call(env)

    puts env.inspect

    status  = 200
    headers = { "Content-Type" => "text/plain" }
    body    = ["\nAHOJ!\n\n"]

    [status, headers, body]
  end
end

app = Application.new

server = ::Puma::Server.new(app)

HOST = 'localhost'
PORT = 9800

ssl_params = {
    'keystore'      => './repro_server+ca.p12',
    'keystore-pass' => '12345678',
    'verify_mode'   => ENV['verify_mode'] || 'none'
}
ssl_context = Puma::MiniSSL::ContextBuilder.new(ssl_params, server.events).context
server.add_ssl_listener(HOST, PORT, ssl_context)

server.run.join
```

Run server with JRuby:
```
verify_mode=peer jruby -Ilib -v repro.rb
```

Than try connecting:
```
curl --verbose --cacert repro_ca.crt --cert repro_client.crt --key repro_client.key https://127.0.0.1:9800
```
output (**unexpected behavior* - server hangs for a while and eventually finished with empty response):
```
*   Trying 127.0.0.1:9800...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 9800 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: repro_ca.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=NA; L=Jungle; O=Puma; CN=server
*  start date: Oct 27 08:20:55 2021 GMT
*  expire date: Jul 23 08:20:55 2024 GMT
*  subjectAltName: host "127.0.0.1" matched cert's IP address!
*  issuer: C=US; ST=NA; L=Jungle; O=Puma; CN=ca
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: 127.0.0.1:9800
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server

```

As far as I checked there are no SSL certificate verification issues from the Java engine - everything seems to be okay.
Seems like the problem is at Puma's.

**Expected behavior**

NOTE: script works as expected with `verify_mode=none jruby -Ilib -v repro.rb`, output:
```
*   Trying 127.0.0.1:9800...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 9800 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: repro_ca.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=NA; L=Jungle; O=Puma; CN=server
*  start date: Oct 27 08:20:55 2021 GMT
*  expire date: Jul 23 08:20:55 2024 GMT
*  subjectAltName: host "127.0.0.1" matched cert's IP address!
*  issuer: C=US; ST=NA; L=Jungle; O=Puma; CN=ca
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: 127.0.0.1:9800
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 8
< 

AHOJ!

* Connection #0 to host 127.0.0.1 left intact
```

**Desktop (please complete the following information):**
 - OS: Linux/Mac Java 11 (`jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.6+10 on 11.0.6+10 +jit [linux-x86_64]`)
 - Puma Version 5.5.2 (also tried master)

### PR DESCRIPTION
**Pull request by kares**
### Description

The native JRuby extension was not utilizing the Java SSL API properly.
With certain buffering scenarios the internal delegated task was not executed.
This lead to issues such as https://github.com/puma/puma/issues/2729 (which contains a reproducer).

Closes #2729 

### Your checklist for this pull request

- [ ] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@kares Thanks again.  Would you like me to cancel the older CI runs?

File: test/test_integration_ssl.rb [hunk 1]
```diff
@@ -93,6 +93,48 @@ def test_ssl_run
     end
   end
 
+  def test_ssl_run_with_curl_client
+    skip_if :windows; require 'stringio'
```
Comment (dentarg) [inline test/test_integration_ssl.rb:97]: @kares was the `stringio` require here intentional?
