### PR TITLE
Fixes the bug that wouldn't allow no_token be set to true

### LINKED ISSUE #1193: Setting no_token option causes crash
### Steps to reproduce

1) Put `{ no_token: true } ` as an option to `activate_control_app` in `puma/config.rb`, for example:
`activate_control_app 'unix:///tmp/pumactl.sock', { no_token: true }`

2) Attempt to start the server with
`pumactl start`

### Expected behavior

Puma should start

### Actual behavior

Puma crashes with the message ```undefined method `rindex' for :none:Symbol```

### System configuration

**Ruby version**: 2.4.0
**Puma version**: 3.6.2

## Notes

This issue can be worked around by using `{ auth_token: '' }`, however the example file suggests the `no_token` syntax, which is broken.

### PR DESCRIPTION
**Pull request by Jesus**
This recovers PR #1321 by @manishval. Closes #1193 

It's the same code as the original PR but it also includes a test to cover the reported bug.

### CODE REVIEW

File: lib/puma/dsl.rb [hunk 1]
```diff
@@ -105,7 +105,7 @@ def activate_control_app(url="auto", opts={})
       end
 
       if opts[:no_token]
-        auth_token = :none
+        auth_token = 'none'
```
Comment (nateberkopec) [inline lib/puma/dsl.rb]: Please add a comment here about why it's important we use a string rather than a symbol. I could see someone trying to "optimize" this later :D

**Comment by nateberkopec** [comment]
Thank you @Jesus! What a resurrection!

Needs one thing added and I think it's good to go.

File: lib/puma/dsl.rb (hunk 1 above)
Comment (dentarg) [reply lib/puma/dsl.rb]: Shouldn't there be tests that fail if changed?

Comment (Jesus) [reply lib/puma/dsl.rb]: @dentarg the test already checks if the value is `'none'` https://github.com/puma/puma/pull/1803/files#diff-5199cb8753ebe54bb452866fea92a0d7R44

If you think there're more cases we should cover I'm willing to know.

Comment (nateberkopec) [reply lib/puma/dsl.rb]: I see what you mean 'dentarg' - yes I know the tests will fail, but still I'd like a record of *why* this is important for the future.

File: test/test_pumactl.rb [hunk 2]
```diff
@@ -29,6 +29,23 @@ def test_config_file
...
   end
 
+  def test_control_no_token
+    opts = [
+      "--config-file", "test/config/control_no_token.rb",
+      "start"
+    ]
+
+    control_cli = Puma::ControlCLI.new opts, @ready, @ready
+    t = Thread.new do
```
Comment (MSP-Greg) [inline test/test_pumactl.rb]: The assert passes with the thread being created.

So, should it be removed, or an assert/refute added for it?

Comment (Jesus) [reply test/test_pumactl.rb]: Sorry I don't understand what you mean. Would you mind elaborating?

Also I think there's a better way to write this test which shouldn't require a thread: I think checking that the value is a String rather than checking that the server boots successfully should be enough.

**Comment by Jesus** [comment]
Thanks Nate for your effort viewing my PRs, I appreciate it a lot!

Please let me sort out what @MSP-Greg is pointing out and this should be ok to go.

File: test/test_pumactl.rb (hunk 2 above)
Comment (nateberkopec) [reply test/test_pumactl.rb]: not sure what @MSP-Greg means either but this test is also nondeterministic - control_cli.run may not finish before we run the assertion

Comment (nateberkopec) [reply test/test_pumactl.rb]: I think you could just fix that with a .join though

Comment (MSP-Greg) [reply test/test_pumactl.rb]: I think the assert statement could be moved above the `Thread.new` statement, or, the instance variable is set with `Puma::ControlCLI.new`, not `#run`.  Sorry, gone for most of the morning...

Comment (Jesus) [reply test/test_pumactl.rb]: I think it's been a mistake trying to test two things in a single test: It was explicitly testing that the value was being set to 'none' and also implicitly testing that the server could boot with `no_token: true`.

I've removed the part about booting the server.

**Comment by Jesus** [comment]
Sorry for the back and forth, I'll use `[WIP]` next time I commit incomplete work on a PR.

This should be ok to go unless you want to add anything further.

**Comment by nateberkopec** [comment]
> Sorry for the back and forth, I'll use [WIP] next time I commit incomplete work on a PR.

Not a problem! I'll merge when it's green.
