### PR TITLE
Always send lowlevel_error response to client

### LINKED ISSUE #2341: Puma sends empty response bodies even when low-level handler is specified
**Describe the bug**

Puma's README [describes the `lowlevel_error_handler` as a way to specify how Puma should react in error conditions outside of the context of your application][0]. Specifically, the docs show that you can return a Rack response with the expectation that Puma will write that response to the client socket.

In practice, though, Puma only writes that response in one particular kind of low-level error, [`server.rb:737`](https://github.com/puma/puma/blob/v4.3.5/lib/puma/server.rb#L737). There are around [six other places][1] where the `lowlevel_error_handler` is invoked, but the return value is just discarded. In these cases, Puma writes the HTTP status line itself to the socket and closes it, without writing headers or a response body.

Since the `lowlevel_error_handler` is invoked in these cases, it's still better than nothing since application developers can still be notified of errors happening if they're reporting the error to their error collection system. But Puma offers no way to customize the response code, response headers, or response body in these cases. Clients just get blank responses.

[0]: https://github.com/puma/puma/blob/0f718d516b92cd8bc4120c543b06792b22ac20bb/README.md#error-handling
[1]: https://github.com/puma/puma/commit/7577a27b5a16fbdd62b5d2162396894c01c7d31b

**Puma config:**

```ruby
lowlevel_error_handler do |e|
  puts "lowlevel_error_handler called"
  [500, {}, ["An error has occurred, and engineers have been informed. Please reload the page. If you continue to have problems, contact support@example.com\n"]]
end
```

**Expected behavior**

Puma writes the Rack response specified in the return value of the `lowlevel_error_handler` in every case that it's invoked.

**Desktop (please complete the following information):**
 - OS: MacOS, Linux
 - Puma Version: 4.3.5

### PR DESCRIPTION
**Pull request by baelter**
### Description
Always send what the lowlevel_error handler returns to the client.

Refactors some code out of `Request#handle_request` to a new `Request#write_response` that can be used from `Server` to send the response from `lowlevel_error`
Closes #2341

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by nateberkopec** [comment]
Thank you for trying to close such a long-standing issue!

File: test/test_puma_server.rb [hunk 1]
```diff
@@ -363,6 +363,17 @@ def test_lowlevel_error_message
     assert (data.size > 0), "Expected response message to be not empty"
   end
 
+  def test_lowlevel_error_handler_custom_response
+    options = { lowlevel_error_handler: ->(_err) { [200, {}, ["error page"]] } }
```
Comment (nateberkopec) [inline test/test_puma_server.rb:367]: Just for the sake of clarity of the test, let's make the status code `500`.

**Review by cjlarose — APPROVED** [review]
Awesome work!

**Comment by cjlarose** [comment]
Changes look good to me. If it looks good to you guys @nateberkopec and @dentarg , I think we're good to merge.

**Comment by dentarg** [comment]
I should disclose that @baelter is my co-worker at 84codes, hence I was quick to look at this one. I think a second approve from someone else would be great, maybe @MSP-Greg if @nateberkopec doesn't have the time right now?

**Review by MSP-Greg — APPROVED** [review]

**Comment by baelter** [comment]
> Awesome work!

Thanks!
