### PR TITLE
lib/rack/handler/puma.rb - fix for rackup v1.0.1, adjust Gemfile

### LINKED ISSUE #3531: System specs break after upgrading to rackup 1.0.1
**Describe the bug**

Hello, I've reported this to rackup repository but it appears to be a problem with Puma.

```
     1.1) Failure/Error: register :puma, Puma
          
          NoMethodError:
            undefined method `register' for Rackup::Handler:Module
```

Some references from rack/rackup#19

> It looks like a problem with Puma:
> 
> https://github.com/puma/puma/blob/v6.4.3/lib/rack/handler/puma.rb#L117-L141
> 
> ```
> if Object.const_defined? :Rackup
> ```
> 
> is probably incorrect.
> 
> There should be two separate files, `lib/rack/handler/puma.rb` and `lib/rackup/handler/puma.rb`. The former is loaded by Rack v2 and the latter by Rackup v2. Having only one file with the detection logic is, basically, looking incorrect to me.
> 
> cc `@MSP-Greg`

> Yes, I think we should report this to Puma.
> 
> Here is how I do it in Falcon:
> 
> https://github.com/socketry/falcon/blob/main/lib/rackup/handler/falcon.rb
> 
> It should be easy to adapt.

**Puma config:**

Default puma 7.2 rails config, but should not be relevant here: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/blob/tmp/rack-rackup-19/config/puma.rb

**To Reproduce**
1. Upgrade rackup to 1.0.1
2. Run system specs driven by a capybara chrome driver

Failure: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/actions/runs/11477074046

**Expected behavior**
Specs keep running

**Desktop (please complete the following information):**
 - OS: n/a
 - Puma Version: 6.4.3
 - Rack version: 2.2

/cc @ioquatix

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description

This almost falls in the category of "Don't get me started...".

It will break things.

Previous versions of `Rackup` also defined `Rackup::Handler`, and Puma assumed that if `Rackup` was defined, so was `Rackup::Handler`.  That is not the case with v1.0.1.  All it defines is `Rackup::VERSION`.  It's simply a Rack 2 compatible version that makes Gemfile logic simpler.  Its gemspec also contains:
```ruby
  spec.add_dependency "rack", "< 3"
  spec.add_dependency "webrick"
```

This PR now checks for the existence of `Rackup::Handler`

Closes #3531

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by ioquatix** [comment]
This PR looks like a reasonable MVP.

I believe you should consider the following (maybe later):

1. Rename `lib/rack/handler/puma.rb` to `lib/puma/rack_handler.rb`.
2. Add the shims `lib/rackup/handler/puma.rb` and `lib/rackup/handler/puma.rb`.

> Previous versions of `Rackup` also defined `Rackup::Handler`.

That's not accurate. `Rackup` v1 never defined `Rackup::Handler`, but it also never defined `Rackup` (because `lib/rackup.rb` was broken). The test here is for the presence of `Rackup` which is insufficient.

Thanks for your efforts.

**Comment by dentarg** [comment]
Hmm, why can't I get the tests to fail without this change? Here's what I tried

```shell
$ git l -1
3f251ae4 (HEAD -> master, dentarg/master) 2024-10-22 11:37:08 -0500 [CI] fix #3325, needs method rename (#3530) (MSP-Greg)

~/src/puma master*
$ git diff
diff --git a/Gemfile b/Gemfile
index 97038b9e..6dfddf50 100644
--- a/Gemfile
+++ b/Gemfile
@@ -11,20 +11,16 @@ gem "minitest-retry"
 gem "minitest-proveit"
 gem "minitest-stub-const"

-use_rackup = false
-rack_vers =
-  case ENV['PUMA_CI_RACK']&.strip
-  when 'rack2'
-    '~> 2.2'
-  when 'rack1'
-    '~> 1.6'
-  else
-    use_rackup = true
-    '>= 2.2'
-  end
-
-gem "rack", rack_vers
-gem "rackup" if use_rackup
+case ENV['PUMA_CI_RACK']&.strip
+when 'rack2'
+  gem "rackup", '~> 1.0'
+  gem "rack"  , '~> 2.2'
+when 'rack1'
+  gem "rack"  , '~> 1.6'
+else
+  gem "rackup", '>= 2.0'
+  gem "rack"  , '>= 2.2'
+end

 gem "jruby-openssl", :platform => "jruby"


~/src/puma master*
$ PUMA_CI_RACK=rack2 bundle
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching rubocop 1.67.0
Installing rubocop 1.67.0
Bundle complete! 15 Gemfile dependencies, 28 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
1 installed gem you directly depend on is looking for funding.
  Run `bundle fund` for details

~/src/puma master*
$ PUMA_CI_RACK=rack2 bundle show | grep rack
  * rack (2.2.10)
  * rackup (1.0.1)

~/src/puma master*
$ PUMA_CI_RACK=rack2 bundle exec ./test/runner -v test_rack_handler
Run options: -v --seed 4592

# Running:

TestRackUp::TestUserSuppliedOptionsIsNotPresent#test_user_port_wins_over_config = 0.02 s = .
TestRackUp::TestUserSuppliedOptionsIsNotPresent#test_config_wins_over_default = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsIsNotPresent#test_user_port_wins_over_default = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsIsNotPresent#test_user_log_requests_wins_over_file_config = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsIsNotPresent#test_default_log_request_when_no_config_file = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsIsNotPresent#test_file_log_requests_wins_over_default_config = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsIsNotPresent#test_user_port_wins_over_default_when_user_supplied_is_blank = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsIsNotPresent#test_default_port_when_no_config_file = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsHostIsSet#test_absolute_unix_host = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsHostIsSet#test_ipv6_host_supplied_port_default = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsHostIsSet#test_abstract_unix_host = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsHostIsSet#test_relative_unix_host = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsHostIsSet#test_ssl_host_supplied_port_default = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsHostIsSet#test_host_uses_supplied_port_default = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsPortIsSet#test_port_wins_over_config = 0.00 s = .
TestRackUp::RackUp#test_bin = /Users/dentarg/.arm64_rubies/3.3.5/bin/rackup:25: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
0.86 s = .
TestRackUp::TestPathHandler#test_handler_boots = 0.50 s = .
TestRackUp::TestUserSuppliedOptionsIsEmpty#test_default_host_when_using_config_file = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsIsEmpty#test_config_file_wins_over_port = 0.00 s = .
TestRackUp::TestUserSuppliedOptionsIsEmpty#test_default_host_when_using_config_file_with_explicit_host = 0.00 s = .
TestRackUp::TestOnBootedHandler#test_on_booted = 0.51 s = .

Fabulous run in 1.894555s, 11.0844 runs/s, 13.1957 assertions/s.

21 runs, 25 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by dentarg** [comment]
Also when I played around "by hand", I could not reproduce either of https://github.com/rack/rackup/issues/13 https://github.com/rack/rackup/issues/19, what am I missing? What's triggering the problem for folks?

```shell
$ cat Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

gem "rackup", "1.0.0"
# gem "rackup", "1.0.1"
gem "puma"

$ b e rackup --server puma
ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Puma starting in single mode...
* Puma version: 6.4.3 (ruby 3.3.5-p100) ("The Eagle of Durango")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 27190
* Listening on http://127.0.0.1:9292
* Listening on http://[::1]:9292
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2024-10-23 22:18:55 +0200 ===
- Goodbye!
```

**Comment by MSP-Greg** [comment]
@dentarg

I think the issue is running Capybara, which starts Puma with `Puma::Server.new` in `lib/capybara/registrations/servers.rb`.  It also has the following line, which is what caused the failure:
```ruby
puma_rack_handler = defined?(Rackup::Handler::Puma) ? Rackup::Handler::Puma : Rack::Handler::Puma
```

I haven't yet thought of a way to add a test.  Also, Capybara no longer tests against Rack 2.  I.think.

**Comment by dentarg** [comment]
I still can't reproduce... I was about to say

```shell
$ bundle
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using rackup 1.0.1 (was 1.0.0)
Bundle complete! 2 Gemfile dependencies, 6 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

~/code-snippets/rackup-test
$ bundle exec ruby -rrack/handler/puma -e 'puma_rack_handler = defined?(Rackup::Handler::Puma) ? Rackup::Handler::Puma : Rack::Handler::Puma; pp puma_rack_handler'
Rack::Handler::Puma
```

So the it is [the `require "rackup"`](https://github.com/teamcapybara/capybara/blob/0480f90168a40780d1398c75031a255c1819dce8/lib/capybara/registrations/servers.rb#L23) that is important

> Using rackup 1.0.1

```shell
$ bundle exec ruby -rrackup -rrack/handler/puma -e 'puma_rack_handler = defined?(Rackup::Handler::Puma) ? Rackup::Handler::Puma : Rack::Handler::Puma; pp puma_rack_handler'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.4.3/lib/rack/handler/puma.rb:126:in `<module:Handler>': undefined method `register' for module Rackup::Handler (NoMethodError)

      register :puma, Puma
      ^^^^^^^^
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.4.3/lib/rack/handler/puma.rb:120:in `<module:Rackup>'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.4.3/lib/rack/handler/puma.rb:119:in `<top (required)>'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
```

> Using rackup 1.0.0

```shell
$ bundle exec ruby -rrackup -rrack/handler/puma -e 'puma_rack_handler = defined?(Rackup::Handler::Puma) ? Rackup::Handler::Puma : Rack::Handler::Puma; pp puma_rack_handler'
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/rackup-1.0.0/lib/rackup.rb:6:in `require_relative': cannot load such file -- /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/rackup-1.0.0/lib/rackup/handler (LoadError)
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/rackup-1.0.0/lib/rackup.rb:6:in `<top (required)>'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
```

**Comment by dentarg** [comment]
Actually, the code we try to run doesn't matter, it is the `require`s, I updated my examples

**Review by dentarg — APPROVED** [review]
`bundle exec ruby -rrackup -rrack/handler/puma -e ''` works fine when pointing puma to this branch in my Gemfile

**Comment by dentarg** [comment]
Hehe, so rackup 1.0.0 has been broken for quite some time but anyone using it only with Capybara hasn't noticed, because Capybara [wraps `require "rackup"` with `rescue LoadError`](https://github.com/teamcapybara/capybara/blob/0480f90168a40780d1398c75031a255c1819dce8/lib/capybara/registrations/servers.rb#L22-L25)

```shell
$ b e ruby -r rackup -e ''
/Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/rackup-1.0.0/lib/rackup.rb:6:in `require_relative': cannot load such file -- /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/rackup-1.0.0/lib/rackup/handler (LoadError)
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/rackup-1.0.0/lib/rackup.rb:6:in `<top (required)>'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
```

When that was fixed today, the bug in Puma was uncovered.

**Comment by tagliala** [comment]
Hello, I've tested https://github.com/diowa/ruby3-rails7-bootstrap-heroku/pull/996 against this branch and it's working again

Please let me know if I can do something, I will try

File: test/test_rack_handler.rb [hunk 1]
```diff
@@ -360,5 +365,26 @@ def test_bin
...
+      io = IO.popen "RUBYOPT='-rbundler/setup -rrack/version -rrack/handler -rrackup -rrack/handler/puma' ruby -e 'puts Rackup::VERSION'"
+      io.wait_readable 2
+      sleep 0.7
+      pid = io.pid
+      log = io.sysread 2_048
+      assert_match(/\A1\./, log)
+    ensure
+      if pid
+        if Puma::IS_WINDOWS
+          `taskkill /F /PID #{pid}`
```
Comment (ioquatix) [inline test/test_rack_handler.rb:383]: Can you not use `Process.kill`?

Comment (MSP-Greg) [reply test/test_rack_handler.rb:383]: I haven't checked for a while, but Windows doesn't handle signals the same as *nix or macos.

I just copied the basic code from `test_bin`, which I think I wrote.  I'll have a look.  Might be tomorrow AM (US).

**Comment by MSP-Greg** [comment]
I added a test.  The test fails on master (rack2 jobs) when the test and Gemfile changes are added to master.
See  https://github.com/MSP-Greg/puma/actions/runs/11490130421

Also, all the `turbo-rails.yml` Rails 7.1 workflows fail in master.
See:  https://github.com/MSP-Greg/puma/actions/runs/11490130416

File: test/test_rack_handler.rb [hunk 2]
```diff
@@ -360,5 +365,26 @@ def test_bin
         end
       end
     end
+
+    def test_rackup1
+      pid = nil
+      # JRuby & TruffleRuby take a long time using IO.popen
+      skip_unless :mri
+      #io = IO.popen "RUBY_OPT='-rrack/handler' rackup -p 0"
+      io = IO.popen "RUBYOPT='-rbundler/setup -rrack/version -rrack/handler -rrackup -rrack/handler/puma' ruby -e 'puts Rackup::VERSION'"
```
Comment (dentarg) [inline test/test_rack_handler.rb:374]: Why the commented line? Is it good to have around if debugging this?

**Review by dentarg — APPROVED** [review]
Test LGTM, thanks for dealing with it

File: test/test_rack_handler.rb (hunk 1 above)
Comment (MSP-Greg) [reply test/test_rack_handler.rb:382]: @ioquatix

Thanks.  I looked at this, and with possible errors being raised, or extra messages to the CI log, this is probably the easiest way to shut a process down, especially with multiple OS's.

But while looking at it, I noticed that I had a bash command line for `IO.popen`, so I updated it to work with Windows by using the `env` parameter for passing `RUBYOPT`.

We don't test Rack2/Rackup on Windows in CI.

**Comment by ioquatix** [comment]
Thanks 🙏

**Comment by franzliedke** [comment]
May I ask for a release including this bugfix? 🙏🏼 

This seems to be blocking a lot of gem upgrades across the ecosystem.

**Comment by cbartlett** [comment]
Would be awesome to get a release for this. Quite a few gem upgrades on several of our projects are blocked by this issue.

**Comment by wenderjean** [comment]
+1 for releasing this

**Comment by rsanheim** [comment]
Any chance for a release on this please? Would help with downstream capybara issues. 🙇

**Comment by JulianKnoche** [comment]
@nateberkopec @MSP-Greg Would it be possible to release this bugfix soon?

**Comment by cbartlett** [comment]
We decided not to wait for a release and instead changed to use a forked Puma:
```ruby
gem 'puma', github: 'nimbleind/puma', branch: 'fix-rack'
```

Anyone can use [this branch](https://github.com/puma/puma/compare/puma:puma:v6.4.3...nimbleind:puma:fix-rack) if you like. It takes the last release of 6.4.3 and adds only the commit that fixes the rackup issue.

This unblocked 12 gem updates for us.

**Comment by heyitscoco** [comment]
Just one more person asking humbly for a release 🙏🏾

**Comment by Francois-gaspard** [comment]
Is there anything we can do to help get this released?

**Comment by larouxn** [comment]
> Just one more person asking humbly for a release 🙏🏾
> Is there anything we can do to help get this released?

Quick heads up that v6.5.0 has been released. :rocket: 

https://github.com/puma/puma/releases/tag/v6.5.0

**Comment by ioquatix** [comment]
Thanks everyone, and apologies for this glitch in the matrix, may they be few and far between!
