### PR TITLE
Make sure low level error response is sent to the client

### LINKED ISSUE #2341: Puma sends empty response bodies even when low-level handler is specified
**Describe the bug**

Puma's README [describes the `lowlevel_error_handler` as a way to specify how Puma should react in error conditions outside of the context of your application][0]. Specifically, the docs show that you can return a Rack response with the expectation that Puma will write that response to the client socket.

In practice, though, Puma only writes that response in one particular kind of low-level error, [`server.rb:737`](https://github.com/puma/puma/blob/v4.3.5/lib/puma/server.rb#L737). There are around [six other places][1] where the `lowlevel_error_handler` is invoked, but the return value is just discarded. In these cases, Puma writes the HTTP status line itself to the socket and closes it, without writing headers or a response body.

Since the `lowlevel_error_handler` is invoked in these cases, it's still better than nothing since application developers can still be notified of errors happening if they're reporting the error to their error collection system. But Puma offers no way to customize the response code, response headers, or response body in these cases. Clients just get blank responses.

[0]: https://github.com/puma/puma/blob/0f718d516b92cd8bc4120c543b06792b22ac20bb/README.md#error-handling
[1]: https://github.com/puma/puma/commit/7577a27b5a16fbdd62b5d2162396894c01c7d31b

**Puma config:**

```ruby
lowlevel_error_handler do |e|
  puts "lowlevel_error_handler called"
  [500, {}, ["An error has occurred, and engineers have been informed. Please reload the page. If you continue to have problems, contact support@example.com\n"]]
end
```

**Expected behavior**

Puma writes the Rack response specified in the return value of the `lowlevel_error_handler` in every case that it's invoked.

**Desktop (please complete the following information):**
 - OS: MacOS, Linux
 - Puma Version: 4.3.5

### PR DESCRIPTION
**Pull request by Vuta**
Closes #2341

### Description

Currently, when Client I/O operations raise any exceptions, we build a fallback rack response (either by `lowlevel_error_handler` or by default puma's hard-coded response), but doesn't do anything with it. This commit ensures that this response is sent back to client.

To verify:
1. `bundle exec puma -C test/config/lowlevel_error_handler.rb test/rackup/hello.ru`
2. `curl -i GET localhost:9292`

```
HTTP/1.1 500 Internal Server Error
Content-Length: 24

something wrong happened
```

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

File: test/test_response_header.rb [hunk 1]
```diff
@@ -49,15 +49,15 @@ def test_integer_key
     server_run app: ->(env) { [200, { 1 => 'Boo'}, []] }
     data = send_http_and_read "GET / HTTP/1.0\r\n\r\n"
 
-    assert_match(/HTTP\/1.1 500 Internal Server Error/, data)
+    assert_match(/HTTP\/1.0 500 Internal Server Error/, data)
```
Comment (nateberkopec) [inline test/test_response_header.rb:52]: 🤔 Huh?

File: lib/puma/server.rb [hunk 2]
```diff
@@ -492,21 +492,29 @@ def with_force_shutdown(client, &block)
...
+    def client_error(e, client, requests = 1)
       # Swallow, do not log
       return if [ConnectionError, EOFError].include?(e.class)
 
-      lowlevel_error(e, client.env)
       case e
       when MiniSSL::SSLError
         @log_writer.ssl_error e, client.io
       when HttpParserError
+        status, headers, res_body = lowlevel_error(e, client.env, 400)
```
Comment (nateberkopec) [inline lib/puma/server.rb:503]: Would you kindly refactor these lines into a method?

```ruby
def respond_to_error(status_code)
status, headers, res_body = lowlevel_error(e, client.env, status_code)
prepare_response(status, headers, res_body, requests, client)
client.write_error(status_code)
end
```

File: test/test_response_header.rb (hunk 1 above)
Comment (Vuta) [reply test/test_response_header.rb]: Previously it failed on some platforms (non MRI or windows I think). This is the full `data`
```
HTTP/1.0 500 Internal Server Error\r\nContent-Length: 659\r\n\r\nPuma caught this error: undefined method `downcase' for 1:Integer (NoMethodError)\n/Users/vutran/learning/puma/lib/puma/request.rb:610:in `block in str_headers'\n/Users/vutran/learning/puma/lib/puma/request.rb:607:in `each'\n/Users/vutran/learning/puma/lib/puma/request.rb:607:in `str_headers'\n/Users/vutran/learning/puma/lib/puma/request.rb:170:in `prepare_response'\n/Users/vutran/learning/puma/lib/puma/request.rb:131:in `handle_request'\n/Users/vutran/learning/puma/lib/puma/server.rb:431:in `process_client'\n/Users/vutran/learning/puma/lib/puma/server.rb:233:in `block in run'\n/Users/vutran/learning/puma/lib/puma/thread_pool.rb:147:in `block in spawn_thread'HTTP/1.1 500 Internal Server Error\r\n\r\n
```

I guess matching against `Puma caught this error: undefined method `downcase' for 1:Integer` would be better?

**Review by nateberkopec — APPROVED** [review]

**Comment by nateberkopec** [comment]
Leaving unmerged to give other maintainers some time to look but LGTM

File: test/config/lowlevel_error_handler.rb
Comment (dentarg) [inline test/config/lowlevel_error_handler.rb:1]: Why is this file added? I fail to see where it is used

File: lib/puma/server.rb [hunk 3]
```diff
@@ -492,22 +492,21 @@ def with_force_shutdown(client, &block)
...
     # Handle various error types thrown by Client I/O operations.
-    def client_error(e, client)
+    def client_error(e, client, requests = 1)
       # Swallow, do not log
       return if [ConnectionError, EOFError].include?(e.class)
 
-      lowlevel_error(e, client.env)
       case e
       when MiniSSL::SSLError
         @log_writer.ssl_error e, client.io
```
Comment (dentarg) [inline lib/puma/server.rb:501]: Looks like your `lowlevel_error_handler` (if you had one) was called for `MiniSSL::SSLError` before but now it is not. Is that a change we want to make?

File: test/test_response_header.rb (hunk 1 above)
Comment (dentarg) [reply test/test_response_header.rb]: @nateberkopec I commented on the same thing with the previous attempt: https://github.com/puma/puma/pull/2731/files#diff-732bb402028f0495d2e1bbcdf2abd9deef82f19e1b5f45711e5e32d450656563

We should understand why this is changing, not just change it

Comment (dentarg) [reply test/test_response_header.rb]: > This is the full `data`

Why does it say `HTTP/1.1 500 Internal Server Error\r\n\r\n` at the end?

What does it say in master?

**Comment by MSP-Greg** [comment]
I need to look at the code more, but is this optional?  I'm not sure if everyone wants backtrace info sent to a client?  Options for logging it, but not to the client, unless development mode? Sorry, busy with other things (reliable CI)...

File: test/test_response_header.rb (hunk 1 above)
Comment (Vuta) [reply test/test_response_header.rb]: > Why does it say HTTP/1.1 500 Internal Server Error\r\n\r\n at the end?

That comes from the `client.write_error(500)`. We can either
1. keep that line and change the regex to make the test pass
2. remove that line completely

I went with (1) because I wasn't sure if (2) has any other implications

File: test/config/lowlevel_error_handler.rb
Comment (Vuta) [reply test/config/lowlevel_error_handler.rb:1]: I followed the instruction in the contributing guide, which says adding it to reproduce the issue. I'm fine with removing it though 🙂

File: lib/puma/server.rb (hunk 3 above)
Comment (Vuta) [reply lib/puma/server.rb:501]: we don't seem to want to sent anything back to client for this error right? because there is no `client.write_error` for it 🤔

**Comment by Vuta** [comment]
> I need to look at the code more, but is this optional? I'm not sure if everyone wants backtrace info sent to a client? Options for logging it, but not to the client, unless development mode? Sorry, busy with other things (reliable CI)...

I think it's optional. If user sets the environment to something other than development and test, the general message `An unhandled lowlevel error occurred. The application logs may have details.` will be sent instead.

File: test/config/lowlevel_error_handler.rb
Comment (nateberkopec) [reply test/config/lowlevel_error_handler.rb:1]: I assumed it was used in the test! Whoops.

Comment (Vuta) [reply test/config/lowlevel_error_handler.rb:1]: thanks, removed!

**Comment by nateberkopec** [comment]
Marking as waiting for review as @vuta has responded to maintainer concerns but we don't have an approve yet.

File: lib/puma/server.rb (hunk 3 above)
Comment (nateberkopec) [reply lib/puma/server.rb:501]: We don't want to send anything, but we still want to call the low-level error handler.

Comment (nateberkopec) [reply lib/puma/server.rb:501]: I think we didn't send anything back in this case because an ssl error usually means we didn't even establish a connection, so there's probably no client to send anything back to. But we absolutely still want to call the error handler, as someone may have a side effect on their error handler to do something like call Sentry or some other error notification service.

Comment (nateberkopec) [reply lib/puma/server.rb:501]: So I guess: we could try to send something back to the client but just not care if it fails?

Comment (Vuta) [reply lib/puma/server.rb]: Thanks for the clarification @nateberkopec. I think it makes sense that we need to call the handler, so I moved the call to the `MiniSSL::SSLError` case

**Comment by MSP-Greg** [comment]
I'll defer to others, but I'm not sure about any responses that might 'fingerprint' Puma's use to clients.

**Comment by dentarg** [comment]
> I'll defer to others, but I'm not sure about any responses that might 'fingerprint' Puma's use to clients.

Fair point considering the recent `Server` header discussions.

It is set here

https://github.com/puma/puma/blob/6d3fd09e2d36bd63ccbb6bc71a980553aed9cc28/lib/puma/server.rb#L544

I guess it is meant to be helpful in cases where you haven't configured the low level handler and something unexpected happens in production... but I agree it is sharing unnecessary details to the end user.

**Comment by Vuta** [comment]
@dentarg thanks. I agree that end users don't need to know about "unhandled lowlevel error" or "application logs". So I removed them altogether.

File: lib/puma/server.rb [hunk 4]
```diff
@@ -541,10 +541,17 @@ def lowlevel_error(e, env, status=500)
         backtrace = e.backtrace.nil? ? '<no backtrace available>' : e.backtrace.join("\n")
         [status, {}, ["Puma caught this error: #{e.message} (#{e.class})\n#{backtrace}"]]
       else
-        [status, {}, ["An unhandled lowlevel error occurred. The application logs may have details.\n"]]
+        [status, {}, ["An error occurred\n"]]
```
Comment (dentarg) [inline lib/puma/server.rb:544]: I'm not sure this is that much better than the previous message, it is probably still somewhat unique to Puma.

I checked what [pitchfork](https://github.com/Shopify/pitchfork) does in [the `500 Internal Server Error` case](https://github.com/Shopify/pitchfork/blob/b5e2bbcbebd22bcd8a212c300e0bc8abbecc4040/test/integration/test_broken_app.rb), and it doesn't respond with any body (`RACK_ENV=development` and `RACK_ENV=production` behaves the same).

```
$ curl -s -v http://127.0.0.1:8080/raise
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /raise HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.84.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
* no chunk, no close, no size. Assume close to signal end
<
* Closing connection 0

$ curl -s -v http://127.0.0.1:8080/nil
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /nil HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.84.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
* no chunk, no close, no size. Assume close to signal end
<
* Closing connection 0
```

File: lib/puma/server.rb [hunk 5]
```diff
@@ -504,22 +504,22 @@ def with_force_shutdown(client, &block)
     # :nocov:
 
     # Handle various error types thrown by Client I/O operations.
-    def client_error(e, client)
+    def client_error(e, client, requests = 1)
       # Swallow, do not log
       return if [ConnectionError, EOFError].include?(e.class)
 
-      lowlevel_error(e, client.env)
```
Comment (nateberkopec) [inline lib/puma/server.rb:511]: Why does MiniSSL::SSLError get slightly different handling now? If I'm reading it right, this branch still has the "bug" of never responding to the client actually?

Comment (Vuta) [reply lib/puma/server.rb:511]: Adding `lowlevel_error` to `MiniSSL::SSLError` so that the handler code can be run, and we don't send anything back to client because there is nothing to send back right? If I understand your previous comment correctly
