### PR TITLE
[Fix #3228] `idle-timeout` not working in cluster mode

### LINKED ISSUE #3228: idle-timeout not shutting down when `workers` are set
# Expected

Puma to shut down after 5 seconds of inactivity.

```
# puma.rb
#
# ... rest of file
# 
# workers ENV.fetch("WEB_CONCURRENCY") { 2 }
```

```
bundle exec puma hello.ru --idle-timeout=5
```

```
➜  git:(main) ✗ bundle exec puma hello.ru --idle-timeout=5
Puma starting in single mode...
* Puma version: 6.4.0 (ruby 3.2.0-p0) ("The Eagle of Durango")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 23471
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2023-09-21 13:14:34 -0700 ===
- Goodbye!
```

# Actual

Puma restarts workers infinitely.

```
# puma.rb
#
# ... rest of file
# 
workers ENV.fetch("WEB_CONCURRENCY") { 2 }
```

``` 
bundle exec puma hello.ru --idle-timeout=5
```

```
➜  git:(main) ✗ bundle exec puma hello.ru --idle-timeout=5
[23279] Puma starting in cluster mode...
[23279] * Puma version: 6.4.0 (ruby 3.2.0-p0) ("The Eagle of Durango")
[23279] *  Min threads: 5
[23279] *  Max threads: 5
[23279] *  Environment: development
[23279] *   Master PID: 23279
[23279] *      Workers: 2
[23279] *     Restarts: (✔) hot (✔) phased
[23279] * Listening on http://0.0.0.0:3000
[23279] Use Ctrl-C to stop
[23279] - Worker 0 (PID: 23405) booted in 0.0s, phase: 0
[23279] - Worker 1 (PID: 23406) booted in 0.0s, phase: 0
[23279] - Worker 0 (PID: 23412) booted in 0.0s, phase: 0
[23279] - Worker 1 (PID: 23411) booted in 0.01s, phase: 0
[23279] - Worker 0 (PID: 23417) booted in 0.01s, phase: 0
[23279] - Worker 1 (PID: 23418) booted in 0.0s, phase: 0
```

**Puma config:**

Default Puma config when initializing a Rails app.

```
# Puma can serve each request in a thread from an internal thread pool.
# The `threads` method setting takes two numbers: a minimum and maximum.
# Any libraries that use thread pools should be configured to match
# the maximum value specified for Puma. Default is set to 5 threads for minimum
# and maximum; this matches the default thread size of Active Record.
#
max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count

# Specifies the `worker_timeout` threshold that Puma will use to wait before
# terminating a worker in development environments.
#
worker_timeout 3600 if ENV.fetch("RAILS_ENV", "development") == "development"

# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
#
port ENV.fetch("PORT") { 3000 }

# Specifies the `environment` that Puma will run in.
#
environment ENV.fetch("RAILS_ENV") { "development" }

# Specifies the `pidfile` that Puma will use.
pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }

# Specifies the number of `workers` to boot in clustered mode.
# Workers are forked web server processes. If using threads and workers together
# the concurrency of the application would be max `threads` * `workers`.
# Workers do not work on JRuby or Windows (both of which do not support
# processes).
#
workers ENV.fetch("WEB_CONCURRENCY") { 2 }

# Use the `preload_app!` method when specifying a `workers` number.
# This directive tells Puma to first boot the application and load code
# before forking the application. This takes advantage of Copy On Write
# process behavior so workers use less memory.
#
# preload_app!

# Allow puma to be restarted by `bin/rails restart` command.
plugin :tmp_restart
```

**To Reproduce**

`hello.ru` file:

```
run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]] }
```

Run it with:

```
bundle exec puma hello.ru --idle-timeout=5
```

# Notes

I initially thought this was because of Scout APM's [Puma worker loop](https://github.com/scoutapp/scout_apm_ruby/blob/a49ea7b34e9d0ef3c988ca96b3360de7f2f523aa/lib/scout_apm/server_integrations/puma.rb#L57-L58), because I was seeing this when also enabling `preload_app` and using `scout_apm`: (on a new Rails app, [which you can clone here](https://github.com/davidalejandroaguilar/scout_apm_puma_idle_timeout)):

```
➜  git:(main) ✗ RAILS_ENV=production SCOUT_DEV_TRACE=true bundle exec puma --idle-timeout=5
[24120] Puma starting in cluster mode...
[24120] * Puma version: 6.4.0 (ruby 3.2.0-p0) ("The Eagle of Durango")
[24120] *  Min threads: 5
[24120] *  Max threads: 5
[24120] *  Environment: production
[24120] *   Master PID: 24120
[24120] *      Workers: 2
[24120] *     Restarts: (✔) hot (✖) phased
[24120] * Preloading application
[24120] * Listening on http://0.0.0.0:3000
[24120] Use Ctrl-C to stop
I, [2023-09-21T13:20:03.516036 #24245]  INFO -- : Installing Puma worker loop.
[24120] - Worker 0 (PID: 24245) booted in 0.0s, phase: 0
I, [2023-09-21T13:20:03.517641 #24246]  INFO -- : Installing Puma worker loop.
[24120] - Worker 1 (PID: 24246) booted in 0.0s, phase: 0
I, [2023-09-21T13:20:08.541142 #24249]  INFO -- : Installing Puma worker loop.
[24120] - Worker 1 (PID: 24249) booted in 0.0s, phase: 0
I, [2023-09-21T13:20:08.541951 #24250]  INFO -- : Installing Puma worker loop.
[24120] - Worker 0 (PID: 24250) booted in 0.0s, phase: 0
```

However, looks like Scout APM [will detect when shutting down](https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/agent.rb#L164-L167), so the real culprit is the `workers` option not allowing Puma to shut down.

# Versions

**Desktop (please complete the following information):**
 - OS: MacOS Monterrey 12.6
 - Puma Version 6.4.0

### PR DESCRIPTION
**Pull request by joshuay03**
### Description

Closes https://github.com/puma/puma/issues/3228.

Ensures that a worker kills the master process if its server shut down due the the idle timeout elapsing. The master will gracefully shut down the rest of the workers and then itself.

~I wonder if we should backport this to https://github.com/puma/puma/tree/v6.4.0 🤔~

Stupid question 🤦🏽‍♂️

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

File: test/test_integration_cluster.rb [hunk 1]
```diff
@@ -221,6 +221,20 @@ def test_worker_timeout
...
+
+    get_worker_pids # wait for workers to boot
+
+    sock = connect
+
+    sleep 1.15
+
+    assert_raises Puma.jruby? ? IOError : Errno::ECONNREFUSED, "Connection refused" do
+      connect
+    end
```
Comment (joshuay03) [inline test/test_integration_cluster.rb:235]: Before:
Screenshot 2023-09-27 at 4 27 24 pm

File: lib/puma/cluster/worker.rb [hunk 2]
```diff
@@ -146,6 +146,8 @@ def run
         # Invoke any worker shutdown hooks so they can prevent the worker
         # exiting until any background operations are completed
         @config.run_hooks(:before_worker_shutdown, index, @log_writer, @hook_data)
+
+        Process.kill "SIGTERM", master if server.idle_timeout_reached
```
Comment (joshuay03) [inline lib/puma/cluster/worker.rb:150]: Trapped here:
https://github.com/puma/puma/blob/252890cc46a4e8fde06399e101fb15cbb412ae46/lib/puma/cluster.rb#L323-L341

File: test/test_integration_cluster.rb [hunk 3]
```diff
@@ -221,6 +221,20 @@ def test_worker_timeout
...
+
+    get_worker_pids # wait for workers to boot
+
+    sock = connect
+
+    sleep 1.15
+
+    assert_raises Errno::ECONNREFUSED, "Connection refused" do
+      connect
+    end
```
Comment (joshuay03) [inline test/test_integration_cluster.rb:235]: Before:
Screenshot 2023-09-27 at 4 27 24 pm

**Comment by nateberkopec** [comment]
> I wonder if we should backport this to https://github.com/puma/puma/tree/v6.4.0 🤔

Did you mean the `5.x` series? I'm happy to do backports if you open a PR against the appropriate `-stable` branch.

**Comment by nateberkopec** [comment]
> I wonder if we should backport this to https://github.com/puma/puma/tree/v6.4.0 🤔

Sorry, what do you mean?

**Review by nateberkopec — APPROVED** [review]

**Comment by joshuay03** [comment]
> > I wonder if we should backport this to [`v6.4.0`](https://github.com/puma/puma/tree/v6.4.0?rgh-link-date=2023-09-28T04%3A34%3A23Z) 🤔
> 
> Sorry, what do you mean?

Sorry, I might be misunderstanding how releases work...

What I'm trying to say is, since the feature was included in https://github.com/puma/puma/releases/tag/v6.4.0, is there a way to include this patch in the same release? 🤔

**Comment by dentarg** [comment]
We (Nate) will have to put out a patch release, 6.4.1.

**Comment by davidalejandroaguilar** [comment]
Thanks for the great and quick work on this! 🥇

**Comment by nateberkopec** [comment]
See #3261

**Comment by dentarg** [comment]
That sounds like a bug to me indeed, and worthy of its own issue so it can be picked up! (Disclaimer: I haven't tested anything myself in regards to this feature)

**Comment by bensheldon** [comment]
I opened #3282

**Comment by joshuay03** [comment]
> Am I understanding that if any single worker hits the idle timeout, it shuts down everything?

Yes that is how this currently works. But,

> It seems like the the `Puma::Cluster` should be checking across all of the workers and then terminating if idle.

this does make more sense to me.

I may have jumped the gun on this one before clarifying the exact implementation based off of https://github.com/puma/puma/issues/3228#issuecomment-1730893957 and https://github.com/puma/puma/issues/3228#issuecomment-1732171992.

I'll tackle https://github.com/puma/puma/issues/3282 sometime today/tomorrow if no one's picked it up by then.
