### PR TITLE
Puma::ControlCLI - allow refork command to be sent as a request

### LINKED ISSUE #2866: "Invalid request command: pumactl refork"
**Describe the bug**
I run puma in refork mode, but when I run `pumactl refork` I just get:
> Invalid request command: refork

`refork` does appear in the list of available commands when I run `pumactl --help`. Sending SIGURG to the main puma process works fine. Other `pumactl` commands, such as gc and stats, work fine.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Puma Version 5.5.0

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description

Currently, the refork command will only be sent as a signal by `Puma::ControlCLI`.  Change to allow it be sent as a request if the control server is setup with a uri.

Closes #2866

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

File: lib/puma/control_cli.rb [hunk 1]
```diff
@@ -33,10 +33,10 @@ class ControlCLI
     COMMANDS = CMD_PATH_SIG_MAP.keys.freeze
 
     # commands that cannot be used in a request
-    NO_REQ_COMMANDS = %w{refork}.freeze
+    NO_REQ_COMMANDS = %w[].freeze
```
Comment (nateberkopec) [inline lib/puma/control_cli.rb:36]: Probably should just remove this constant then, yes?

Comment (nateberkopec) [reply lib/puma/control_cli.rb:36]: I feel like I'm missing something.

Comment (MSP-Greg) [reply lib/puma/control_cli.rb:36]: I can, but I thought I'd leave the code in case a 'signal only' command was added.  Or, previous to this PR, `refork` was a signal only command, and I never tested it using a control server that had a control uri.

Leaving as is means that CI will check that if one is added.  Ok, I know it's a little odd...

Comment (MSP-Greg) [reply lib/puma/control_cli.rb]: I commented out the constant and the clause that used it.  Same for the test (skipped if the constant is undefined).

I can remove if you want...  I just don't want myself or someone else making the same mistake again, so the commented code leave a **big** hint...

File: lib/puma/control_cli.rb [hunk 2]
```diff
@@ -32,11 +32,13 @@ class ControlCLI
     # @deprecated 6.0.0
     COMMANDS = CMD_PATH_SIG_MAP.keys.freeze
 
+    # Uncomment below statement & clause in run method statement if needed
+    #
     # commands that cannot be used in a request
-    NO_REQ_COMMANDS = %w{refork}.freeze
+    # NO_REQ_COMMANDS = %w[].freeze
```
Comment (johnnyshields) [inline lib/puma/control_cli.rb:38]: Should just remove this altogether?

**Comment by MSP-Greg** [comment]
I rebased and added 'signal only' commands that were previously unavailable using `ControlCLI`. See https://github.com/puma/puma/pull/2868/commits/eb87fe59dc4098c1add5f2f9b19027fe1ae8b91b

I think I found all of them.  Hence, `ControlCLI` can be used to send all signal commands that work with the main Puma process.
