### PR TITLE
systemd - fix event firing

### LINKED ISSUE #2572: [phased-restart] add support for systemd type notify
The PR #2438 added support for systemd services of type `notify`.

```ruby
# lib/puma/systemd.rb
module Puma
  class Systemd
    ...
    
    def hook_events
      @events.on_booted { SdNotify.ready }
      @events.on_stopped { SdNotify.stopping }
      @events.on_restart { SdNotify.reloading }
    end
    
    ...
  end
end
```

**The Problem:**  
The systemd status gets updated as expected when performing a `hot restart`.  
But the status stays `active` when performing a `phased restart`.  
In the current implementation, `SdNotify.reloading` is never called during a `phased restart`.

**A Common Scenario:**  
If we perform a `phased restart`, Puma terminates an old worker and starts a new one.
And if Puma is not able to boot up a new worker for some reason, it keeps trying.

In this case, the systemd status shouldn't stay active.  
During a `phased restart` the status should be reloading.

**Additional Context:**  
We monitor the status of all our systemd processes.  
If the status of a process is not active any more (for a certain period of time), we get notified.

It would be awesome to keep this monitoring approach for Puma as well.

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description

Fixes event firings needed for systemd integration.

Closes #2572.

Note that `@events.fire_on_stopped!` was not called when in cluster mode, this also fixes that.

These tests take some time, I tested locally with two restarts, it passed.

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
Note to self - cluster requires fork... 2nd CI Arjun should pass...

File: test/test_integration_systemd.rb [hunk 1]
```diff
@@ -59,4 +56,28 @@ def test_systemd_watchdog
     stop_server
     assert_match(socket_message, "STOPPING=1")
   end
+
+  private
+
+  def restart(signal, workers: 2)
```
Comment (nateberkopec) [inline test/test_integration_systemd.rb:62]: Stylistically, I think every test should end with `assert` or, rarely, a cleanup step or two. This method is basically a set of assertions, so I think it would be appropriate to call it `assert_restarts_with_systemd` or similar.
