### PR TITLE
fix update phased restart symlink folder

### LINKED ISSUE #3290: Phased restart & symlinks doesn't change destination folder?
My puma config

```
directory "/home/prj/current"
rackup "/home/prj/current/config.ru"

environment "staging"
pidfile "/home/prj/shared/tmp/pids/puma.pid"

state_path "/home/prj/shared/tmp/pids/puma.state"
stdout_redirect '/home/prj/shared/log/puma_access.log', '/home/prj/shared/log/puma_error.log', true

bind 'unix:///home/prj/shared/tmp/sockets/puma.sock'

workers 2
max_threads_count = 16
min_threads_count = 1
threads min_threads_count, max_threads_count

prune_bundler

on_worker_boot do
  require "active_record"
  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
  ActiveRecord::Base.establish_connection
end

before_fork do
  ActiveRecord::Base.connection_pool.disconnect! if defined?(ActiveRecord)
end
```

current symlink

```
lrwxrwxrwx 1 deploy deploy   38 Dec  7 12:22 current -> /home/prj/releases/20231207032212/
```

after pharsed-restart

```
cat /home/prj/current/tmp/pids/puma.state 
---
pid: 4475
running_from: "/home/prj/releases/20231206070847"

ps aux | grep puma
deploy      4475  0.0  1.1 105820 11392 ?        Ss   Dec06   0:05 puma 6.4.0 (unix:///home/prj/shared/tmp/sockets/puma.sock) [20231206070847]
deploy     22985  0.1 16.6 785688 162364 ?       Sl   12:42   0:04 puma: cluster worker 0: 4475 [20231206070847]
deploy     23001  0.1 22.7 812040 221384 ?       Sl   12:42   0:04 puma: cluster worker 1: 4475 [20231206070847]

ls /home/prj/releases/
20231206073136  20231206073247  20231207032212
```

its seem like puma still working on old release folder?

### PR DESCRIPTION
**Pull request by nikhilbhatt**
### Description
Fixes #3290 

During phased restart updated the tag name with folder base name if tag is not set in puma config.

### Your checklist for this pull request

- [ ] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by dentarg** [comment]
Any idea how we could test this?

**Comment by nikhilbhatt** [comment]
> Any idea how we could test this?

**If you are asking about testing the branch, here how I done it**

Temporary changes
1. cd to puma latest version.
2. Create a folder releases/1 and releases/2 folder.
3. Copy file hello.ru to both the releases and update the content if needed.
4. create link `ln -s releases/1/ current`
6. Update settings.rb file and add following
    ```
    workers 2
    directory 'path to current'
    prune_bundler
   ```
7. run `bundle exec bin/puma -C "absolute path to test/config/settings.rb" hello.ru`
8. grep for `puma`
9. unlink current
10. `ln -s releases/2/ current`
11.  kill -SIGUSR1 `puma_pid`
12. again grep for `puma` to view updated changes.

for 2nd testing update `settings.rb` with additional `tag testing`.
when you repeat above steps there should be no change in tags.

**If you are asking about writing test cases for this**
I am looking into this.

File: test/test_worker_gem_independence.rb [hunk 1]
```diff
@@ -142,4 +145,10 @@ def with_unbundled_env
       Bundler.with_unbundled_env { yield }
     end
   end
+
```
Comment (nikhilbhatt) [inline test/test_worker_gem_independence.rb:148]: @dentarg 

Added testcases in `TestWorkerGemIndependence`. not sure if it should be in separate or new class.

also used grep here as I did not find any alternative to get the title of Process running. we are using `setproctitle` to set the title but there is not equivalent for this to get.

**Comment by nikhilbhatt** [comment]
@dentarg can you check this once?

**Comment by dentarg** [comment]
I'll check whenever, no stress in open source

**Comment by nikhilbhatt** [comment]
Is there anything remaining in this from my side?

**Comment by nateberkopec** [comment]
Sorry for the delay, ya caught me right when I had a kid 😆
