### PR TITLE
[Fix #2786] Worker 0 timing out during phased restart

### LINKED ISSUE #2786: `fork_worker` worker termination during phased-restart
**Describe the bug**

During `phased-restart`, while running with `fork_worker` option, worker 0 stops to receive **ping** message. While the puma process is running, constantly we are doing `timeout_workers`, which checks if workers are responding. Because worker 0, is not receiving "p" message (ping), it is not updating `@last_checkin` value (WorkerHandle class), which leads to throwing `Terminating timed out worker...` error after exceeding timeout (default: 60), which kills it and starts the loop once again. We end up in the state where `puma` constantly restarting its workers. 

**Puma config:**

```
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
threads threads_count, threads_count

port        ENV.fetch("PORT") { 3000 }

environment ENV.fetch("RAILS_ENV") { "development" }

preload_app! false

fork_worker 0
```

**To Reproduce**
It is quite easy to reproduce this using "hello world" rack application. The only thing you need to do, just run the application using a lot of workers, in my example **32** was more than enough to trigger the behavior.

Spin puma process:
`bundle exec puma -C config/puma.rb -e development --threads 4:16 --workers 32 --tag test --pidfile tmp/puma.pid --state tmp/puma.state --dir . --control-url auto hello.ru`

Trigger phased-restart:
`pumactl -s tmp/puma.state phased-restart`

**Logs with additional puts**

https://github.com/puma/puma/blob/cec07ac780755755351462fed254f7edd2752631/lib/puma/cluster.rb#L454
in `when "p"` add `p "worker: #{w.index}, pid: #{w.pid} received p msg!" if w.index == 0` [**lib/puma/cluster.rb:448**]

https://github.com/puma/puma/blob/a2bcda414377ee3f5855a66ed83aa41ce6f0a29d/lib/puma/cluster.rb#L516
add `p "timeout_workers: #{w.ping_timeout}, pid: #{w.pid}, booted: #{w.booted?}, index: #{w.index}, term: #{w.term?}" if w.index == 0` [**lib/puma/cluster.rb:518**]

**Log looks like this:**
It is easy to see, once phased restart started ping message is not sent to worker 0, and `ping_timeout` value for worker 0 is not being updated, even though it is healthy and responding.
```
"timeout_workers: 2022-01-04 19:04:07 +0200, pid: 9827, booted: true, index: 0, term: false"
[9814] - Worker 31 (PID: 9858) booted in 0.07s, phase: 0
"timeout_workers: 2022-01-04 19:04:07 +0200, pid: 9827, booted: true, index: 0, term: false"
"worker: 0, pid: 9827 received p msg!"
"timeout_workers: 2022-01-04 19:04:07 +0200, pid: 9827, booted: true, index: 0, term: false"
"worker: 0, pid: 9827 received p msg!"
"timeout_workers: 2022-01-04 19:04:12 +0200, pid: 9827, booted: true, index: 0, term: false"
"worker: 0, pid: 9827 received p msg!"
"timeout_workers: 2022-01-04 19:04:17 +0200, pid: 9827, booted: true, index: 0, term: false"
"worker: 0, pid: 9827 received p msg!"
[9814] - Starting phased worker restart, phase: 1
[9814] + Changing to .
"timeout_workers: 2022-01-04 19:04:22 +0200, pid: 9827, booted: true, index: 0, term: false"
[9814] - Stopping 9827 for phased upgrade...
[9814] - TERM sent to 9827...
"timeout_workers: 2022-01-04 19:04:22 +0200, pid: 9827, booted: true, index: 0, term: true"
[9814] - Worker 0 (PID: 9878) booted in 0.02s, phase: 1
"timeout_workers: 2022-01-04 19:04:25 +0200, pid: 9878, booted: true, index: 0, term: false"
[9814] - Stopping 9828 for phased upgrade...
[9814] - TERM sent to 9828...
"timeout_workers: 2022-01-04 19:04:25 +0200, pid: 9878, booted: true, index: 0, term: false"
[9814] - Worker 1 (PID: 9891) booted in 0.0s, phase: 1
"timeout_workers: 2022-01-04 19:04:25 +0200, pid: 9878, booted: true, index: 0, term: false"
[9814] - Stopping 9829 for phased upgrade...
[9814] - TERM sent to 9829...
"timeout_workers: 2022-01-04 19:04:25 +0200, pid: 9878, booted: true, index: 0, term: false"
[9814] - Worker 2 (PID: 9892) booted in 0.0s, phase: 1
"timeout_workers: 2022-01-04 19:04:25 +0200, pid: 9878, booted: true, index: 0, term: false"
[9814] - Stopping 9830 for phased upgrade...
[9814] - TERM sent to 9830...
"timeout_workers: 2022-01-04 19:04:25 +0200, pid: 9878, booted: true, index: 0, term: false"
[9814] - Worker 3 (PID: 9894) booted in 0.0s, phase: 1
"timeout_workers: 2022-01-04 19:04:25 +0200, pid: 9878, booted: true, index: 0, term: false"
[9814] - Stopping 9831 for phased upgrade...
[9814] - TERM sent to 9831...
"timeout_workers: 2022-01-04 19:04:25 +0200, pid: 9878, booted: true, index: 0, term: false"
[9814] - Worker 4 (PID: 9895) booted in 0.0s, phase: 1
"timeout_workers: 2022-01-04 19:04:25 +0200, pid: 9878, booted: true, index: 0, term: false"
**[9814] - Stopping 9832 for phased upgrade...**
[9814] - TERM sent to 9832...
...
```

**Expected behavior**
Once worker 0 is restarted we should send a ping "p" message to its thread as well, and not wait until all the workers is up and running.

**Desktop:**
 - OS: Mac
 - Puma Version: 5.5.2

### PR DESCRIPTION
**Pull request by joshuay03**
### Description

Closes https://github.com/puma/puma/issues/2786.

Ensures that worker 0 is pinged on every forked worker's post-boot ping to prevent it from timing out.

~An integration test for this would be something like https://github.com/puma/puma/issues/2786#issuecomment-1704766900 but might not be practical considering the time it takes. I'll add some unit tests when I get a chance unless anyone has a better idea.~

I've added a regression test with a lowered worker timeout to simulate a high worker count + high worker timeout real world scenario.

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

File: lib/puma/cluster.rb [hunk 1]
```diff
@@ -536,9 +549,9 @@ def timeout_workers
       @workers.each do |w|
         if !w.term? && w.ping_timeout <= Time.now
           details = if w.booted?
-                      "(worker failed to check in within #{@options[:worker_timeout]} seconds)"
+                      "(Worker #{w.index} failed to check in within #{@options[:worker_timeout]} seconds)"
                     else
-                      "(worker failed to boot within #{@options[:worker_boot_timeout]} seconds)"
+                      "(Worker #{w.index} failed to boot within #{@options[:worker_boot_timeout]} seconds)"
```
Comment (joshuay03) [inline lib/puma/cluster.rb:554]: I'm happy to move this to a separate PR if deemed irrelevant. The reasoning here is that the boot logs include both the index and the pid, so I updated this for consistency. Logs before are visible here: https://github.com/puma/puma/issues/2786#issuecomment-1704766900.

**Comment by joshuay03** [comment]
Thanks! @MSP-Greg

**Comment by MSP-Greg** [comment]
@joshuay03

Thanks for the PR.  It's certainly an issue with lots of workers and threads.  Locally, I don't think I ever tried a large number of workers. 

I'm wondering about a test, but after making several typos while watching a US football game...

File: test/test_integration_cluster.rb [hunk 2]
```diff
@@ -284,6 +284,29 @@ def test_fork_worker_spawn
...
+
+    while (line = @server.gets).include?("phase: 0")
+      # wait till all the workers are up
+      break if line.include?("Worker 10")
+    end
+
+    Process.kill :USR1, @pid
+
+    while (line = @server.gets)
+      refute line.include?("Terminating timed out worker")
```
Comment (joshuay03) [inline test/test_integration_cluster.rb:305]: Before (with line logs):
```ruby
puma [phased-restart-worker-0-timing-out] bundle exec m test/test_integration_cluster.rb:290
Run options: -n "/^(test_fork_worker_phased_restart_with_high_worker_count)$/" --seed 26090

# Running:

"[40482] - Worker 0 (PID: 40487) booted in 0.0s, phase: 0\n"
"[40482] - Worker 1 (PID: 40488) booted in 0.0s, phase: 0\n"
"[40482] - Worker 2 (PID: 40489) booted in 0.0s, phase: 0\n"
"[40482] - Worker 3 (PID: 40490) booted in 0.0s, phase: 0\n"
"[40482] - Worker 4 (PID: 40491) booted in 0.01s, phase: 0\n"
"[40482] - Worker 5 (PID: 40492) booted in 0.01s, phase: 0\n"
"[40482] - Worker 6 (PID: 40493) booted in 0.01s, phase: 0\n"
"[40482] - Worker 7 (PID: 40494) booted in 0.01s, phase: 0\n"
"[40482] - Worker 8 (PID: 40495) booted in 0.01s, phase: 0\n"
"[40482] - Worker 9 (PID: 40496) booted in 0.01s, phase: 0\n"
"[40482] - Worker 10 (PID: 40497) booted in 0.01s, phase: 0\n"
"[40482] - Starting phased worker restart, phase: 1\n"
"[40482] + Changing to /Users/joshuayoung/Projects/puma\n"
"[40482] - Stopping 40487 for phased upgrade...\n"
"[40482] - TERM sent to 40487...\n"
"[40482] - Stopping 40487 for phased upgrade...\n"
"[40482] - Worker 0 (PID: 40506) booted in 0.01s, phase: 1\n"
"[40482] - Stopping 40488 for phased upgrade...\n"
"[40482] - TERM sent to 40488...\n"
"[40482] - Worker 1 (PID: 40513) booted in 0.0s, phase: 1\n"
"[40482] - Stopping 40489 for phased upgrade...\n"
"[40482] - TERM sent to 40489...\n"
"[40482] ! Terminating timed out worker (Worker 0 failed to check in within 6 seconds): 40506\n"
F

Fabulous run in 11.535691s, 0.0867 runs/s, 1.1269 assertions/s.
Errors & Failures:

  1) Failure:
TestIntegrationCluster#test_fork_worker_phased_restart_with_high_worker_count [/Users/joshuayoung/Projects/puma/test/test_integration_cluster.rb:305]:
Expected true to not be truthy.

1 runs, 13 assertions, 1 failures, 0 errors, 0 skips
```

Comment (joshuay03) [reply test/test_integration_cluster.rb:305]: Passing test takes ~33s so we're 👍🏽

**Comment by MSP-Greg** [comment]
@joshuay03

I've also worked on a test, I've got one working with the PR and failing with master.  But, it involves some changes to one of the helper files, and it's tanked all the JRuby CI.  Of course, it works with JRuby locally...

I decided to look at it tomorrow with a 'fresher' set of eyes.

**Comment by MSP-Greg** [comment]
@joshuay03

Thanks again for this.  Using `@server.gets` may involve a bit of blocking, which can be problematic with parallel testing and CI servers running with multiple VM's.

Can you rebase and use the following?  I've tried to rebase PR's before, and things seem to go south when I've then done a force push.  Note that I dropped the worker count to 10.

JFYI, this only possible with a rebase, as I just added `@server_log`, which is the server log that's accumulated as any method that reads the server log output is called.  `get_worker_pids` waits for all the workers to be booted, 1st parameter is the phase...

Thanks.


```ruby
  def test_fork_worker_phased_restart_with_high_worker_count
    worker_count = 10

    cli_server "test/rackup/hello.ru", config: <<~RUBY
      fork_worker 0
      worker_check_interval 1
      # lower worker timeout from default (60) to avoid test timeout
      worker_timeout 2
      # to simulate worker 0 timeout, total boot time for all workers
      # needs to exceed single worker timeout
      workers #{worker_count}
    RUBY

    # workers is the default
    get_worker_pids 0, worker_count

    Process.kill :USR1, @pid

    get_worker_pids 1, worker_count

    # below is so all of @server_log isn't output for failure
    refute @server_log[/.*Terminating timed out worker.*/]
  end
```

**Comment by joshuay03** [comment]
@MSP-Greg

Done 👍🏽 This setup is much better, thanks for that!

**Review by MSP-Greg — APPROVED** [review]
