### PR TITLE
:bug Fix error_logger inproperly logging `env[QUERY_STRING]`

### LINKED ISSUE #3617: Puma::ErrorLogger: missing "?" when logging requests with a query string
```diff
diff --git a/lib/puma/error_logger.rb b/lib/puma/error_logger.rb
index 792e14a6..a12fba67 100644
--- a/lib/puma/error_logger.rb
+++ b/lib/puma/error_logger.rb
@@ -78,13 +78,13 @@ module Puma
     def request_title(req)
       env = req.env
 
       REQUEST_FORMAT % [
         env[REQUEST_METHOD],
         env[REQUEST_PATH] || env[PATH_INFO],
-        env[QUERY_STRING] || "",
+        (qs = env[QUERY_STRING]) && !qs.empty? ? "?#{qs}" : "",
         env[HTTP_X_FORWARDED_FOR] || env[REMOTE_ADDR] || "-"
       ]
     end
 
     def request_headers(req)
       headers = req.env.select { |key, _| key.start_with?('HTTP_') }
```

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description

As noted in title.

Three commits:

1. **ci: test_error_logger.rb - add test_info_with_request_with_query_param** - this commit can be checked out and the added test will fail.  Replaced several regex assertions with `assert_include`
2. **error_logger.rb - fixup QUERY_STRING bug (no ? output)** - fixes bug
3. **ci: tests.yml - quote 3.0, otherwise parsed as 3** - GHA yaml parser works differently than Ruby.  A version with a trailing zero must be quoted.  `3.0` will be interpreted as `3` which currently loads 3.4.z and `3.10`, which would load Ruby 3.1.z.

Closes #3625
Closes #3617

@bhooshiek-narendiran and @olleolleolle - sorry, this seemed easier.  I listed the two of you as co-authors

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

File: test/test_error_logger.rb [hunk 1]
```diff
@@ -40,15 +40,32 @@ def test_info_with_request
...
+    req = Req.new(env, '{"hello":"world"}')
+
+    _, err = capture_io do
+      Puma::ErrorLogger.stdio.info(error: StandardError.new, req: req)
+    end
+
+    assert_includes err,  'GET /debug?b=test" - (8.8.8.8))'
+  end
+
+
```
Comment (olleolleolle) [inline test/test_error_logger.rb]: 👾 An extra newline we could do without?
