### PR TITLE
Fix out_of_band hook

### LINKED ISSUE #2177: out_of_band hook not working when using multiple threads
**Describe the bug**
The `out_of_band` hook (C.F. https://github.com/puma/puma/pull/1648) seems not to work when the number of threads specified with `threads N, N` is `> 1`.

**Puma config:**

```
threads 2, 2
port        ENV.fetch("PUMA_PORT") { 3000 }
environment ENV.fetch("RAILS_ENV") { "development" }
workers ENV.fetch("PUMA_WORKERS") { 1 }

out_of_band do
  puts 'OOB Hook Working'
end

preload_app!

plugin :tmp_restart
```

Command: `bundle exec puma -C config/puma.rb oob.ru`

Contents of `oob.ru`:
```
run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]] }
```

**To Reproduce**
1. Make sure `config/puma.rb` and `oob.ru` have the contents showed above
2. Run `bundle exec puma -C config/puma.rb oob.ru`
3. Make some requests: `curl http://127.0.0.1:3000/`
4. Note that `OOB Hook Working` does NOT get printed in Puma output

Now, to show it works with `threads 1, 1`:
1. Stop the Puma server if already running
2. Replace `threads 2, 2` in the Puma config with `threads 1, 1`
3. Run `bundle exec puma -C config/puma.rb oob.ru`
4. Make some requests: `curl http://127.0.0.1:3000/`
5. Note that `OOB Hook Working` IS present in Puma output

**Expected behavior**
I expect `out_of_band` hook to be called even when Puma is configured to run with multiple threads.

**Desktop:**
 - OS: Mac OS X 10.14
 - Puma Version: 4.3.3

### PR DESCRIPTION
**Pull request by wjordan**
### Description
Fixes #2177. (Thanks @GuiTeK for tracking down this bug!)

Modifies the `out_of_band` hook implementation in the `Server` class to ensure that hooks are fired as expected when the server is configured with >1 max threads.

Compare to #2178, #2180. This implementation is pretty simple. It changes behavior slightly by executing the hooks on the same thread that finished processing the last request (instead of the main acceptor thread), so the server can continue accepting incoming requests if any arrive while the out-of-band hooks are still executing.

I've also added a couple of server tests to ensure out-of-band hooks fire as expected in two scenarios (sequential and parallel requests).

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` the pull request title.
- [x] I have added appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
I just switched to a different 'apt-get' server, so Ubuntu should pass consistently, I think.

File: lib/puma/thread_pool.rb [hunk 1]
```diff
@@ -79,6 +79,10 @@ def pool_capacity
       waiting + (@max - spawned)
     end
 
+    def busy_threads
+      @spawned - @waiting + @todo.size
```
Comment (nateberkopec) [inline lib/puma/thread_pool.rb:83]: I think we need to wait for the @mutex here if not already held. This will work on MRI but won't work on JRuby/etc.

File: lib/puma/dsl.rb [hunk 2]
```diff
@@ -494,8 +494,9 @@ def after_worker_fork(&block)
 
     # Code to run out-of-band when the worker is idle.
     # These hooks run immediately after a request has finished
-    # processing and there are no busy threads on the worker.
-    # The worker doesn't accept new requests until this code finishes.
```
Comment (nateberkopec) [inline lib/puma/dsl.rb:498]: Whoops, that wasn't ever true, was it?

Comment (nateberkopec) [reply lib/puma/dsl.rb:498]: Also, Q: should this be the actual behavior? Is it really OOB otherwise?

**Comment by nateberkopec** [comment]
Only Q for me is: should the OOB hook work the way it was advertised? "No other requests will be processed until the hook finishes". 

Both approaches have the potential to add latency to requests.

File: lib/puma/dsl.rb (hunk 2 above)
Comment (wjordan) [reply lib/puma/dsl.rb:498]: > Whoops, that wasn't ever true, was it?

The oob hook previously ran from the acceptor thread, so I think it _was_ true at least for the case where it was working correctly (max threads 1).

> should this be the actual behavior? Is it really OOB otherwise?

Hmm, I went back and forth on whether it's better to keep accepting new requests while an OOB hook is running. (Might depend on the hook's use case?) For GC optimization at least, I thought continuing to accept requests could potentially be better under high load (though the MRI GVL could make it a wash). But on second thought, _not_ accepting new requests is probably safer for light loads especially while request-balancing is still uneven. Plus it is 'really OOB' for other use-cases. I can change this to run on the acceptor thread as before.

File: lib/puma/thread_pool.rb (hunk 1 above)
Comment (wjordan) [reply lib/puma/thread_pool.rb]: Done in ff28636f2ccd274569ed29c7bc5d505d5d96ba87 - not 100% sure if this approach (calling `@mutex.owned?` in a `with_mutex` wrapper method) has any small perf implications we care about. Alternative would be to not use a method at all, or introduce a `in_mutex` argument.

File: lib/puma/dsl.rb (hunk 2 above)
Comment (wjordan) [reply lib/puma/dsl.rb]: Updated in 7b3639125d8591103db7962f88531208ca716aff

**Comment by nateberkopec** [comment]
Hm. I think that if the method is called `oob`, it needs to actually be `oob` - so:

1. Grab the threadpool mutex. If we are the only busy thread, then:
2. Stop accepting requests.
3. Run callbacks, return.
4. Start accepting requests.

**Comment by nateberkopec** [comment]
@wjordan thoughts on https://github.com/puma/puma/pull/2218#issuecomment-611351606?

**Comment by nateberkopec** [comment]
Oh OK, that's definitely better than interacting with the threadpool 👍

File: lib/puma/server.rb [hunk 3]
```diff
@@ -439,6 +436,12 @@ def process_client(client, buffer)
         rescue StandardError => e
           @events.unknown_error self, e, "Client"
         end
+
+        if @options[:out_of_band]
+          @thread_pool.with_mutex do
```
Comment (ayufan) [inline lib/puma/server.rb:441]: Does this actually create a mutex now on `thread_pool`? The `OOB` hook is executed within a mutex, rather than dispatched to be executed.

This also, connected with a test `#test_out_of_band_stream` creates a very strong dependency on execution:
the test assumes that all connections are in fact processed concurrently, but this might not always be true, because should we assume that `threads=1`, kind of similar to executing `Puma` with `threads=1`. The test does fail in this condition, as this is being executed on down failing edge of the event.
